version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements
      - run:
          command: python Test/CreateTestDatabase.py
          name: Test create database
      - run:
          command: python Test/UnitTest.py
          name: Run unitTest
      - run:
          command: python Test/TestControl.py
          name: Test control database

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
